FROM python:3.9-slim

ENV MYSQL_ROOT_PASSWORD=12345
ENV MYSQL_USE=user
ENV MYSQL_PASSWORD=12345

WORKDIR /app
COPY requirements.txt ./
RUN pip install -r requirements.txt
COPY main.py ./
CMD ["python", "main.py"]
